### PR TITLE
chore: add updated template for the railway

### PR DESCRIPTION
**Pull request by warengonzaga**
## Changes

- Replace the template with an updated version.

Template: https://railway.app/template/fcEVay

---

## PR-Codex overview
The focus of this PR is to update the deployment option link in the README.md file to point to a new Railway template.

### Detailed summary
- Updated the deployment link to Railway template `fcEVay`.
- Replaced the previous Railway deployment button with a new one.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by warengonzaga** [comment]
I removed the referral code as when you share the Railway markdown version the referral code is enabled by default.

**Comment by warengonzaga** [comment]
Abort, will unpublish the template, the original creator wants to keep the template.

**Comment by warengonzaga** [comment]
Hey, @arcoraven, can you review this?

As [discussed here](https://help.railway.app/templates/thirdweb-engine-7bd7e574), the original template creator offers to unpublish the original template so we can use the template we made for the Railway. Our new template follows the standard and recommended deployment steps for the engine, ensuring every deployment succeeds.

Moving forward, I'll provide technical support to the railway community to ensure that any engine deployment will work as expected and maintain a 100% success rate.

**Review by farhanW3 — APPROVED** [review]

**Comment by warengonzaga** [comment]
Let's merge this @farhanW3 or @arcoraven so people can use the official community template.

**Pull request merged**
