### PR TITLE
fix: User guide docs

### PR DESCRIPTION
**Pull request by KovacZan**
## Changes

Fixed a typo in `docs/1-user-guide.md`. 
The previous value was wrong.

### CODE REVIEW

**Comment by farhanW3** [comment]
@KovacZan Thanks for the PR. if you can get the latest from `main`, this might already be addressed, if not I will merge this in.

**Comment by KovacZan** [comment]
> @KovacZan Thanks for the PR. if you can get the latest from `main`, this might already be addressed, if not I will merge this in.

@farhanW3 It has been addressed already. You can close this PR.

**Comment by farhanW3** [comment]
Thank you @KovacZan

**Comment by farhanW3** [comment]
changes already made, closing PR

**Pull request closed without merging**
